package tn.esprit.cupcake.gui;


import com.codename1.capture.Capture;
import com.codename1.components.ImageViewer;
import com.codename1.components.SpanLabel;
import com.codename1.components.ToastBar;

import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.io.Util;
import com.codename1.system.NativeLookup;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Component;
import com.codename1.ui.ComponentGroup;
import com.codename1.ui.Container;
import com.codename1.ui.EncodedImage;
import com.codename1.ui.Font;
import com.codename1.ui.FontImage;
import com.codename1.ui.Graphics;
import com.codename1.ui.Image;
import com.codename1.ui.TextField;
import com.codename1.ui.URLImage;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.events.DataChangedListener;
import com.codename1.ui.geom.Dimension;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.Style;
import java.util.Random;
import tn.esprit.cupcake.entities.AI;
import tn.esprit.cupcake.entities.TTS;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication2 extends BaseForm {
  private String userName;
    private Image userPicture;
    private Form current;
    private TTS tts;

    public void init(Object context) {
        Resources theme = UIManager.initFirstTheme("/theme");
        userPicture = theme.getImage("duke_iphone.png");
        tts = (TTS)NativeLookup.create(TTS.class);        
        // Pro only feature, uncomment if you have a pro subscription
        //Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Bienvenue Cher Client : que puis je faire pour vous aider ?");
        BorderLayout bl = new BorderLayout();
        bl.setCenterBehavior(BorderLayout.CENTER_BEHAVIOR_CENTER);
        hi.setLayout(bl);
        hi.setFormBottomPaddingEditingMode(true);
       
        ComponentGroup cg = new ComponentGroup();
         EncodedImage encImg  = EncodedImage.createFromImage(UIManager.initFirstTheme("/theme").getImage("robotchef2.png"),false);
      ImageViewer image = new ImageViewer(encImg);
        final TextField name = new TextField();
        name.setHint("Quelle est votre nom?");
        cg.add(image);
        cg.addComponent(name);
        
        
        hi.addComponent(BorderLayout.CENTER, cg);
        Toolbar t = new Toolbar();
        hi.setToolBar(t);
        t.addCommandToRightBar(new Command("Next") {
            @Override
            public void actionPerformed(ActionEvent evt) {
                userName = name.getText();
                if(userName.length() == 0) {
                    userName = "[Unnamed]";
                }
                showSbaitso();
            }
        });
        hi.show();
    }

    private DataChangedListener createSearchListener(final TextField searchField, final Container discussion, final Button ask) {
        return new DataChangedListener() {
            private boolean animateLock;
            public void dataChanged(int type, int index) {
                String t = searchField.getText();
                int count = discussion.getComponentCount();
                if(t.length() == 0) {
                    ask.setEnabled(true);
                    for(int iter = 0 ; iter < count ; iter++) {
                        Component c = discussion.getComponentAt(iter);
                        c.setPreferredSize(null);
                        c.setVisible(true);
                    }
                    animateChanage();
                    return;
                }              
                t = t.toLowerCase();
                ask.setEnabled(false);
                for(int iter = 0 ; iter < count ; iter++) {
                    SpanLabel tt = (SpanLabel)discussion.getComponentAt(iter);
                    if(tt.getText().toLowerCase().indexOf(t) < 0) {
                        tt.setPreferredSize(new Dimension(1, 1));
                        tt.setVisible(false);
                    } else {
                        tt.setPreferredSize(null);
                        tt.setVisible(true);
                    }
                }
                animateChanage();
            }
            private void animateChanage() {
                if(!animateLock) {
                    animateLock = true;
                    discussion.animateLayoutAndWait(300);
                    animateLock = false;
                }
            }
        };        
    }
    
    void showSbaitso() {
        Form sb = new Form();
        sb.setFormBottomPaddingEditingMode(true);
        Toolbar t = new Toolbar();
        sb.setToolBar(t);
        t.addCommandToRightBar(new Command("Quitter") {
            @Override
            public void actionPerformed(ActionEvent evt) {
               TrendingForm tf = new TrendingForm();
               tf.show();
                
            }
        });
        final TextField searchField = new TextField();
        searchField.setHint("Cherche en cours...");
//        t.setTitleComponent(searchField);
        sb.setLayout(new BorderLayout());
        final TextField ask = new TextField();
        ask.setHint("Posez moi une question");
        Container askContainer = new Container(new BorderLayout());
        askContainer.addComponent(BorderLayout.CENTER, ask);
        Button askButton = new Button("Envoyé");
        askContainer.addComponent(BorderLayout.EAST, askButton);        
        sb.addComponent(BorderLayout.SOUTH, askContainer);
        final Container discussion = new Container(new BoxLayout(BoxLayout.Y_AXIS));
        sb.addComponent(BorderLayout.CENTER, discussion);
        discussion.setScrollableY(true);
        sb.show();
        Display.getInstance().callSerially(new Runnable() {
            public void run() {
                          String w = "Bonjour" +" "+ userName +", Je m'appelle Javis je suis le guide de Cupcake  Vous Pouvez Me Posez Des  Questions  .";

                say(discussion, w, false);
                if(tts != null && tts.isSupported()) {
                    tts.say(w);
                }
            }
        });
        searchField.addDataChangeListener(createSearchListener(searchField, discussion, askButton));
        ActionListener askEvent = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String t = ask.getText();
                if(t.length() > 0) {
                    ask.setText("");
                    say(discussion, t, true);
                    answer(t, discussion);
                }
            }
        };
        ask.setDoneListener(askEvent);
        askButton.addActionListener(askEvent);
    }
    
    void answer(String question, Container dest) {
        String resp = AI.getResponse(question);
        say(dest, resp, false);
        if(tts != null && tts.isSupported()) {
            tts.say(resp);
        }
    }
    
    void say(Container destination, String text, boolean question) {
        SpanLabel t = new SpanLabel(text);
        t.setWidth(destination.getWidth());
        t.setX(0);
        t.setHeight(t.getPreferredH());
        
        if(question) {
            t.setY(Display.getInstance().getDisplayHeight());
            t.setTextUIID("BubbleUser");
            t.setIconPosition(BorderLayout.EAST);
            t.setIcon(userPicture);
            t.setTextBlockAlign(Component.RIGHT);
        } else {
            t.setY(0);
            t.setTextUIID("BubbleSbaitso");
            t.setTextBlockAlign(Component.LEFT);
        }
        destination.addComponent(t);
        destination.animateLayoutAndWait(400);
        destination.scrollComponentToVisible(t);
    }
    
    private Image roundImage(Image img) {
        int width = img.getWidth();
        Image roundMask = Image.createImage(width, width, 0xff000000);
        Graphics gr = roundMask.getGraphics();
        gr.setColor(0xffffff);
        gr.fillArc(0, 0, width, width, 0, 360);
        Object mask = roundMask.createMask();
        img = img.applyMask(mask);
        return img;
    }
    
    private Image captureRoundImage() {
        try {
            int width = userPicture.getWidth();
            String result = Capture.capturePhoto(width, -1);
            if(result == null) {
                return userPicture;
            }
            Image capturedImage = Image.createImage(result);
            if(capturedImage.getHeight() != width) {
                if(capturedImage.getWidth() < capturedImage.getHeight()) {
                    capturedImage = capturedImage.subImage(0, capturedImage.getHeight() / 2 - width / 2, width, width, false);
                } else {
                    Image n = Image.createImage(width, width);
                    n.getGraphics().drawImage(capturedImage, 0, width / 2- capturedImage.getHeight() / 2);
                    capturedImage = n;
                }
            }
            return roundImage(capturedImage);
        } catch (IOException err) {
            err.printStackTrace();
            return userPicture;
        }
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }
}
